---
version: "3.4"
services:
  kt:
    image: myobplatform/kt:2.3.1
    volumes:
      - "$HOME/.kube:/root/.kube"
      - "$HOME/.aws:/root/.aws"
      - ".:/app"
    environment:
      AWS_REGION: "ap-southeast-2"

  lint:
    volumes:
      - ".:/yaml"
    image: sdesbure/yamllint
    entrypoint:
      - yamllint
    command:
      - -d
      - "{extends: default, rules: {line-length: {max: 120, level: warning}}}"
      - "./envs"
