---
version: "3.4"
services:
  stackup:
    image: realestate/stackup:1.4.1
    volumes:
      - "$HOME/.aws:/root/.aws"
      - ".:/app"
    working_dir: /app
    entrypoint: stackup
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2

  gomplate:
    image: hairyhenderson/gomplate:v3.0.0-slim
    volumes:
      - ".:/app"
    working_dir: /app

  awscli:
    image: cgswong/aws:1.16.39
    working_dir: /app
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
    volumes:
      - .:/app
      - $HOME/.aws:/root/.aws
