---
AWSTemplateFormatVersion:  "2010-09-09"
Description: "This stack contains service user and its permission control"


Parameters:
  AllowedCidrRanges:
    Description: AllowedCidr used to the bastion
    Type: String
  BastionSSHKeyName:
    Description: SSHkey name for the bastion box.
    Type: String
  BastionInstanceType:
    Description: Instance type for bastion ec2 box.
    Type: String
    Default: t2.nano
  EnvironmentName:
    Description: EnvironmentName aka stack identifier
    Type: String
  AllowedCidrRanges:
    Description: AllowedCidr used to the bastion
    Type: String
  BastionSSHKeyName:
    Description: SSHkey name for the bastion box.
    Type: String
  HostedZoneID:
    Description: "hosted zone id for the new sub domain"
    Type: String
  DomainName:
    Description: "domain name want to register"
    Type: String
  DockerVersion:
    Description: docker image tag
    Type: String
    Default: "latest"
  KeyName:
    Description: Application ssh login keypair name
    Type: AWS::EC2::KeyPair::KeyName
    Default: "sinatra"


Resources:

  sinatraCiBotGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: sinatraCiBotGroup
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AWSCertificateManagerFullAccess
        - arn:aws:iam::aws:policy/AmazonRoute53AutoNamingFullAccess
        - arn:aws:iam::aws:policy/AutoScalingFullAccess
      Policies:
        - PolicyName: CiUserCFN
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - cloudformation:CreateStack
              - cloudformation:CreateChangeSet
              - cloudformation:ListStacks
              - cloudformation:UpdateStack
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackResource
              - cloudformation:DescribeStackEvents
              - cloudformation:ValidateTemplate
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:DeleteStack
              Resource:
              - "*"
        - PolicyName: CiUserAppStackPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - ec2:DescribeKeyPairs
              - ec2:RevokeSecurityGroupEgress
              - ec2:AuthorizeSecurityGroupEgress
              Resource:
              - "*"
            - Effect: Allow
              Action:
              - iam:GetRole
              - iam:PassRole
              - iam:CreateRole
              Resource:
              - "*"

        - PolicyName: CiUserBastionStackPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - iam:CreateRole
              - iam:DeleteRolePolicy
              - iam:DeleteRole
              - iam:PutRolePolicy
              - iam:CreateInstanceProfile
              - logs:CreateLogGroup
              - logs:DescribeLogGroups
              - logs:DeleteLogGroup
              - logs:PutRetentionPolicy
              - ec2:CreateSecurityGroup
              - ec2:DeleteSecurityGroup
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:createTags
              - iam:AddRoleToInstanceProfile
              - iam:RemoveRoleFromInstanceProfile
              Resource:
              - "*"
        - PolicyName: CiUserDnsStackPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - route53:GetChangeRequest
              - route53:GetChange
              Resource:
              - "*"

  CiUser:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - sinatraCiBotGroup
      UserName: !Sub ${EnvironmentName}-travis-ci
