---
global:
  amiID: "ami-08c26730c8ee004fa"

artifactStore:
  name: wp-content-2019

app:
  keyPairName: "wp"

bastion:
  allowedCidrRanges: "0.0.0.0/0"
  bastionAmiID: "ami-09b42976632b27e9b"
  bastionSSHKeyName: "wp"
  instanceType: "t2.nano"

dns:
  hostedZoneID: "Z1V33XO4AGPWSX"

infra:
  vpcCIDR: "192.168.0.0/16"
  publicSubnetCIDR:
    - "192.168.0.0/20,"
    - "192.168.16.0/20,"
    - "192.168.32.0/20,"
    - "192.168.96.0/20"
  privateSubnetCIDR:
    - "192.168.48.0/20,"
    - "192.168.64.0/20,"
    - "192.168.80.0/20"
  availabilityZones:
    - ' "ap-southeast-2a",'
    - '"ap-southeast-2b",'
    - '"ap-southeast-2c" '
  vpcFlowLogRetention: "3"
