{{- $config := (datasource "config") -}}
---
AWSTemplateFormatVersion:  "2010-09-09"
Description: "This stack contains service user and its permission control"
Resources:

  wpCiBotGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: wpCiBotGroup
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AWSCertificateManagerFullAccess
        - arn:aws:iam::aws:policy/AmazonRoute53AutoNamingFullAccess
        - arn:aws:iam::aws:policy/AutoScalingFullAccess
      Policies:
        - PolicyName: CiUserCFN
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - cloudformation:CreateStack
              - cloudformation:CreateChangeSet
              - cloudformation:ListStacks
              - cloudformation:UpdateStack
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackResource
              - cloudformation:DescribeStackEvents
              - cloudformation:ValidateTemplate
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:DeleteStack
              Resource:
              - "*"
        - PolicyName: CiUserAppStackPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - ec2:DescribeKeyPairs
              - ec2:RevokeSecurityGroupEgress
              - ec2:AuthorizeSecurityGroupEgress
              Resource:
              - "*"
            - Effect: Allow
              Action:
              - iam:GetRole
              - iam:PassRole
              - iam:CreateRole
              Resource:
              - "*"

        - PolicyName: CiUserBastionStackPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - iam:CreateRole
              - iam:DeleteRolePolicy
              - iam:DeleteRole
              - iam:PutRolePolicy
              - iam:CreateInstanceProfile
              - logs:CreateLogGroup
              - logs:DescribeLogGroups
              - logs:DeleteLogGroup
              - logs:PutRetentionPolicy
              - ec2:CreateSecurityGroup
              - ec2:DeleteSecurityGroup
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:createTags
              - iam:AddRoleToInstanceProfile
              - iam:RemoveRoleFromInstanceProfile
              Resource:
              - "*"
        - PolicyName: CiUserDnsStackPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - route53:GetChangeRequest
              - route53:GetChange
              Resource:
              - "*"

  CiUser:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - wpCiBotGroup
      UserName: {{ $config.global.environmentName }}-travis-ci
